dbt_tutorial:
  outputs:
    dev:
      catalog: dbt_tutorial
      host: dbc-95ebaf0f-b557.cloud.databricks.com
      http_path: /sql/1.0/warehouses/ad66c79562f593c9
      schema: default
      threads: 1
      token: 
      type: databricks
    prod:
      catalog: prod_dbt
      host: 
      http_path: /sql/1.0/warehouses/ad66c79562f593c9
      schema: default
      threads: 1
      token: 
      type: databricks
  target: dev
