version: 2

sources:
  - name: source # this is the source_name
    database: dbt_tutorial
    schema: source
    tables:
      - name: fact_sales # this is the table_name
      - name: fact_returns
      - name: dim_date
      - name: dim_store
      - name: dim_product
      - name: dim_customer
      - name: items